AWSTemplateFormatVersion: 2010-09-09
Description: lms Project CloudFormation template.
Resources:
  lmsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
       - Key: Name
         Value: lms-vpc
  
  lmswebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-web-subnet

  lmsapiSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-api-subnet

  lmsdbSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: "false"
      Tags:
      - Key: Name
        Value: lms-database-subnet

  lmsInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: lms-internet-gateway

  lmsAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: lmsVPC
      InternetGatewayId:
        Ref: lmsInternetGateway

  lmsRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: lmsVPC
      Tags:
      - Key: Name
        Value: lms-public-routeTable
    
  lmsinternetRoute:
    Type: AWS::EC2::Route
    DependsOn: lmsAttachGateway
    Properties:
       RouteTableId:
         Ref: lmsRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: lmsInternetGateway
      
  lmswebSubnetRouteTableAssociation:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
    SubnetId:
     Ref: lmswebSubnet
    RouteTableId:
       Ref: lmsRouteTable

  lmsapiSubnetRouteTableAssociation:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
    SubnetId:
     Ref: lmsapiSubnet
    RouteTableId:
       Ref: lmsRouteTable

  lmsprivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: lmsVPC
      Tags:
      - Key: Name
        Value: lms-private-routeTable

  lmsdbSubnetRouteTableAssociation:
   Type: AWS::EC2::SubnetRouteTableAssociation
   Properties:
    SubnetId:
     Ref: lmsdbSubnet
    RouteTableId:
       Ref: lmsprivateRouteTable

   lmswebSubnetNetworkAclAssociation:
     Type: AWS::EC2::SubnetNetworkAclAssociation
     Properties:
       SubnetId:
        Ref: lmswebSubnet
       NetworkAclId:
         Ref: lmsRouteTable